{% set name = "compas_cgal" %}
{% set version = "0.1.1" %}
{% set hash = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
#   url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
#   sha256: {{ hash }}
  path: ../

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - eigen
  host:
    - pip
    - python
    - pybind11
    - cgal-cpp >=5.0
  run:
    - python {{ python }}
    - eigen
    - cgal-cpp >=5.0
    - boost-cpp
    - mpir  # [win]
    - gmp  # [not win]
    - mpfr

test:
  imports:
    - compas_cgal

about:
  home: https://github.com/compas-dev/compas_cgal
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: 'COMPAS friendly wrappers for CGAL algorithms.'
  dev_url: https://github.com/compas-dev/compas_cgal
  doc_url: https://github.com/compas-dev/compas_cgal

extra:
  recipe-maintainers:
    - brgcode
    - gonzalocasas
