name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          activate-environment: cgal
          channels: conda-forge
          python-version: 3.7

      - name: Create conda env (mac)
        if: matrix.os == 'macos-latest'
        run: |
          conda install python.app eigen boost-cpp gmp mpfr cgal-cpp">=5.0" pybind11 COMPAS">=0.16.0" -y
      
      - name: Create conda env (windows)
        if: matrix.os == 'windows-latest'
        run: |
          conda install eigen boost-cpp mpir mpfr cgal-cpp">=5.0" pybind11 COMPAS">=0.16.0" -y
    
      - name: Install compas_cgal
        run: |
          python -m pip install -r requirements-dev.txt 
          python -m pip install -e .
  
      - name: Lint with flake8
        run: |
          invoke lint

      - name: Test with pytest
        run: |
          invoke test
